# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: grocery_store_frontend
on:
  push:
    branches:
      - main
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        working-directory: ./grocery_front_end
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run build
  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          working-directory: ./grocery_front_end
          node-version: 18
          registry-url: https://registry.npmjs.org/
          run: |
            if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
            elif [ -e package-lock.json ]; then
            npm ci
            else
            npm i
            fi
            npm run build
        env:
          NODE_AUTH_TOKEN: ${{secrets.GIT_HUB_GROCERY_STORE}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
